### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Alice77bai** [esjo93/NTIRE-2021-Dehazing-Challenge#1]
Can you provide the data set of Ntire21? It is no longer available for download on the official website, thank you very much

**Comment by esjo93** [comment]
I found the dataset is sill available.
You need to sign in and register the competition to download the dataset.
Then, you can access the dataset on the "participate" tab.  :)

**Comment by njtzy** [comment]
i cannot find validation ground truth on the website do you have some?
